- id: gitleaks
  name: gitleaks
  description: Download and run gitleaks binary
  entry: bash_hooks/gitleaks.sh
  language: script
  pass_filenames: false
- id: forbidden-imports
  name: forbidden-imports
  description: Check for forbidden imports specified in args bn
  entry: forbidden-imports
  language: python
  types: [python]
- id: disallowed-identifiers
  name: disallowed-identifiers
  description: Check for disallowed identifiers specified in args bn
  entry: disallowed-identifiers
  language: python
  types: [python]
- id: deptry
  name: deptry
  entry: uv run deptry .
  language: system
  pass_filenames: false
- id: do-not-support-generated-columns
  name: do-not-support-generated-columns
  entry: do-not-support-generated-columns
  language: python
  types: [sql]
- id: validate-branch-name
  name: validate-branch-name
  description: Checks that branch name is in the expected format
  entry: validate-branch-name
  language: python
  types: [python]
  pass_filenames: false
- id: image-tag-branch-constraint
  name: image-tag-branch-constraint
  description: Check for image_tag and branch
  entry: image-tag-branch-constraint
  language: python
  types: [python]
- id: no-non-spark-buckets-in-spark-projects
  name: no-non-spark-buckets-in-spark-projects
  description: Check for non-Spark bucket imports in projects using tatari-pyspark or tatari-ml-utils
  additional_dependencies: [toml]
  entry: no-non-spark-buckets-in-spark-projects
  language: python
  types: [python]
- id: no-boto3-in-airflow-dags
  name: no-boto3-in-airflow-dags
  description: Prevent direct boto3 imports that cause scheduler abuse via parse-time AWS calls
  entry: no-boto3-in-airflow-dags
  language: python
  types: [python]
- id: no-hardcoded-buckets
  name: no-hardcoded-buckets
  description: Check for hardcoded Tatari S3 bucket names
  entry: no-hardcoded-buckets
  language: python
  types: [python]
- id: app-constraints
  name: app-constraints
  description: Evaluate if uv (PEP 621) dependency constraints for applications follow Tatari's standards
  additional_dependencies: [toml]
  entry: app-constraints
  language: python
  pass_filenames: false
  files: ^pyproject\.toml$
- id: pkg-constraints
  name: pkg-constraints
  description: Evaluate if uv (PEP 621) dependency constraints for packages follow Tatari's standards
  additional_dependencies: [toml]
  entry: pkg-constraints
  language: python
  pass_filenames: false
  files: ^pyproject\.toml$
- id: dockerfile
  name: dockerfile
  description: Check if Dockerfile pins a uv version on install
  entry: dockerfile
  language: python
  files: .*Dockerfile.*
