---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

env:
  UV_VERSION: "0.11.31"
  PYTHON_VERSION: "3.10"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{env.UV_VERSION}}
          python-version: ${{env.PYTHON_VERSION}}
      - run: make unit-test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{env.UV_VERSION}}
          python-version: ${{env.PYTHON_VERSION}}
      - name: cache pre-commit
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{runner.os}}-${{env.PYTHON_VERSION}}-${{hashFiles('.pre-commit-config.yaml')}}
      - run: make lint

  type-check:
    name: Type Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{env.UV_VERSION}}
          python-version: ${{env.PYTHON_VERSION}}
      - run: make type-check
