---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

env:
  POETRY_VERSION: "1.4.2"
  PYTHON_VERSION: "3.9"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install Poetry
        shell: bash
        run: |
          pip3 install poetry==${{env.POETRY_VERSION}}
          poetry config virtualenvs.create false
      - name: Install Poetry Dependencies
        env:
          PYTHONUSERBASE: ""
          SETUPTOOLS_USE_DISTUTILS: "stdlib"
        shell: bash
        run: poetry install
      - run: make unit-test

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install Poetry
        shell: bash
        run: |
          pip3 install poetry==${{env.POETRY_VERSION}}
          poetry config virtualenvs.create false
      - name: Install Poetry Dependencies
        env:
          PYTHONUSERBASE: ""
          SETUPTOOLS_USE_DISTUTILS: "stdlib"
        shell: bash
        run: poetry install
      - run: make lint

  type-check:
    name: Type Checks
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install Poetry
        shell: bash
        run: |
          pip3 install poetry==${{env.POETRY_VERSION}}
          poetry config virtualenvs.create false
      - name: Install Poetry Dependencies
        env:
          PYTHONUSERBASE: ""
          SETUPTOOLS_USE_DISTUTILS: "stdlib"
        shell: bash
        run: poetry install
      - run: make type-check
